# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c552d2686ca8a78fd52e757caedc186691095c3e91b2c65bcceefee634e0c9f65faf3774f36d6e35c3c5060798923a3e959f03a33b92eecbf6de345226e2c054

test:
  secret_key_base: 41b51527f5f436959d8b7856bd7321de37742fb2f35d9ee9f31650ec04139d7a1cabccc2f4a646d6a5fa18ab9c30eb6a8e9780dc32d18ddb8d309b76a6532c5b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
